# Generated by Django 4.1.4 on 2022-12-23 03:42

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='TrailersInf',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.TextField()),
                ('category', models.TextField()),
                ('year', models.IntegerField(max_length=4)),
                ('director', models.TextField()),
                ('actors', models.TextField()),
                ('review', models.IntegerField(max_length=1)),
                ('img_link', models.TextField()),
                ('link', models.TextField()),
            ],
        ),
    ]
