# Generated by Django 4.1.4 on 2022-12-24 13:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('TrailersPage', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='trailersinf',
            name='review',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='trailersinf',
            name='year',
            field=models.IntegerField(),
        ),
    ]
